### ISSUE TITLE
[BUG][DEPLOY] start script shows incorrect webconsole address

### ISSUE THREAD

**Issue by pmorie** [open-cluster-management/deploy#16]
**Describe the bug**
The start script shows an incorrect console URL:

```
Pods still NOT running  : 14
Detected ACM Console URL: https://multicloud-console.apps.acm-dev-pmorie.devcluster.openshift.com
```

The correct URL is `https://multicluster-console.apps.acm-dev-pmorie.devcluster.openshift.com/`

**To Reproduce**

`start.sh --watch`

**Expected behavior**
The right URL

**Comment by pmorie** [comment]
That URL didn't load either, but DID serve https, vs connection interrupted at the URL in the text.

**Comment by pmorie** [comment]
Weird, I guess something did eventually show up behind this URL, closing.

**Comment by tpouyer** [comment]
`multicloud-console` is the route that we are exposing... however that should probably change to `muilticluster-console` for consistency. @joeg-pro 

The script executes the `kubectl apply` against the templated yaml resources... even the `--watch` option is pretty simplistic in what it does...  We should probably add a bit of logic to ensure that all pods are in `RUNNING` state before exposing the console url.  @jnpacker

**Comment by jnpacker** [comment]
Yeah, its just been a problem in the past, having the dev teams keep the list up to date.

And yeah, there is a ticket discussing changing that to multicluster instead of multicloud.

**Comment by jnpacker** [comment]
I was thinking of tracking the deployments as there are fewer of those.
1. I'll add the code to do that this weekend.
2. The URL is from the ingress package, so when they make a change, we'll get the new URL.

**Comment by joeg-pro** [comment]
@tpouyer Thanks for the heads up on `multicloud-console`.  Yea, that was on my list of things to get a ticket open for to rename clooud -> cluster.

@jnpacker Can you post a ref here to the ticket you mention already being open for this?  Thanks.

**Comment by jnpacker** [comment]
@tpouyer https://github.com/open-cluster-management/backlog/issues/855
It didn't directly call it out in the ticket, I realized we had the discussion in slack. it's now referenced near the bottom of 855
