### ISSUE TITLE
[FEATURE] Check if default StorageClass is defined

### ISSUE THREAD

**Issue by niklaushirt** [open-cluster-management/deploy#20]
**Is your feature request related to a problem? Please describe.**
When no default StorageClass is defined, the deployment fails

**Describe the solution you'd like**
Specify in the Doc that a default StorageClass must be set.
Annotation:
`storageclass.kubernetes.io/is-default-class`

And if possible check in the deployment script:

```
SC_RESOLVE=$(oc get sc 2>&1)

if [[ $SC_RESOLVE =~ (default) ]];
then
  echo "    OK: Default Storage Class defined"
else 
  echo "    ERROR: No default Storage Class defined."
  echo "         Define Annotation: storageclass.kubernetes.io/is-default-class=true"
  echo "         Aborting."
  exit 1
fi
```

**Comment by tpouyer** [comment]
This has now been added to the `start.sh` script in master... closing this issue.
