### ISSUE TITLE
[BUG][DEPLOY] Update default snapshot tag due topology-aggregator error

### ISSUE THREAD

**Issue by davivcgarcia** [open-cluster-management/deploy#30]
**Describe the bug**

Using the current default snapshot version `1.0.0-SNAPSHOT-2020-03-30-18-55-25` the deployment fails with error on `topology-aggregator` pods due unavailable tag: `Failed to pull image "quay.io/open-cluster-management/topology-aggregator:0.0.1-SNAPSHOT-2020-03-30-17-01-26": (...) Error reading manifest 0.0.1-SNAPSHOT-2020-03-30-17-01-26 in quay.io/open-cluster-management/topology-aggregator: unauthorized: access to the requested resource is not authorized`

**To Reproduce**

1. Execute `./start.sh --watch` with default values.

**Expected behavior**

Deployment finishes successfully.

**Comment by tpouyer** [comment]
topology-aggregator pods are no longer being included in the product... currently these will show with image pull backoff error, but do not impede the ability to use the tool... there is a fix in the works to remove topology-aggregator from the product entirely so you will not see the image pull backoff error you are seeing now...

Once that fix makes it's way into the latest snapshots I'll close this issue... until then I'll leve this open for others to see.

**Comment by tpouyer** [comment]
I've tagged a new snapshot that can be used to deploy OCM that will not deploy `topology-aggregator`... `SNAPSHOT-2020-03-30-21-19-06`.

Closing this issue.
