### ISSUE TITLE
[BUG][DEPLOY] internal testathon feedback

### ISSUE THREAD

**Issue by berenss** [open-cluster-management/deploy#46]
**Describe the bug**

> Hints/Notes: If the correct snapshot format (1.0.0-SNAPSHOT-2020-04-01-02-43-31) is not used then the start.sh script used to install ACM will timeout and fail at Wait for multiclusterhub-operator to reach running state (4min). The default snapshot will also be replaced with the mistyped snapshot. To resolve use the correct snapshot format when prompted and the script will run successfully.
> 
> Also the script will also fail at Wait for multiclusterhub-operator to reach running state (4min). if the correct pull-secret is not used. Make sure when generating the pull secret from Quay, you select Kubernetes Secret as it will generate the wrong format. You'll see in the script an error at apply per-requisites with the pull secret if the wrong one is used. "Failed to read Resources YAML file [pull-secret.yaml] encounters a format error.

Are we handling the above in deploy doc or improvements to the `start.sh` ? eg, script can verify format of the user-provided snapshot.  script can verify quay credentials prior to beginning the pulls.

**Comment by tpouyer** [comment]
I have added some additional formating logic to the deploy repo to handle the snapshot format:

https://github.com/open-cluster-management/deploy/blob/master/start.sh#L76-L85

For the quay pull-secret I will look at what I can do to validate that although I'm not entirely sure how much validation logic I can add for that.
